version: '3.8'
services:
  api:
    build: ./Server
    container_name: api_backend
    ports:
      - '5002:5002'
    volumes:
      - ./Server:/server
      - /Server/node_modules
    restart: on-failure
  client:
    build: ./Client
    container_name: client_frontend
    ports:
      - '3000:3000'

